export enum API {
  login = 'user/login',
  user = 'user',
  create = 'user/create',
  update = 'user/update/',
  upload = 'user/upload/usuario/',
  delete = 'user/delete/',
  pc = 'pc',
  pcCreate = 'pc/create',
  pcDelete = 'pc/delete',
  pcUpdate = 'pc/update',
  pcupload = 'pc/upload/pc/',
  memory = 'memoria',
  memoryCreate = 'memoria/create',
  memoryUpdate = 'memoria/update',
  memoryDeleted = 'memoria/delete',
  imgUser = 'img/usuario/',
  imgPC = 'img/pc/',
  imgOtros = 'img/otros/',
  imgMemoria = 'memoria/img/',
}
